{
  "headers": {
    "host": "localhost:8088",
    "connection": "keep-alive",
    "content-length": "22",
    "sec-ch-ua": "\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Microsoft Edge\";v=\"120\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
    "content-type": "application/json",
    "accept": "*/*",
    "origin": "http://localhost:8088",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8088/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/multiply",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/multiply",
  "listenerPath": "/api/*",
  "relativePath": "/api/multiply",
  "localAddress": "/127.0.0.1:8088",
  "uriParams": {},
  "rawRequestUri": "/api/multiply",
  "rawRequestPath": "/api/multiply",
  "remoteAddress": "/127.0.0.1:50141",
  "requestPath": "/api/multiply"
}